# Generated by Django 5.2.2 on 2025-06-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
