# Generated by Django 5.2.1 on 2025-07-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_fingerprinttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
    ]
