# Generated by Django 5.2.1 on 2025-07-25 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_activitylog_details_remove_activitylog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprinttemplate',
            name='user_id',
        ),
        migrations.AddField(
            model_name='fingerprinttemplate',
            name='voter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voting.voter'),
            preserve_default=False,
        ),
    ]
