# Generated by Django 5.2.1 on 2025-07-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_remove_fingerprinttemplate_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='email',
        ),
        migrations.AddField(
            model_name='voter',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
