# Generated by Django 5.2.1 on 2025-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_voter_email_voter_age_voter_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('register', 'Register'), ('match', 'Match')], max_length=20)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_used'], name='voting_scantrigger_is_used_idx'), models.Index(fields=['created_at'], name='voting_scantrigger_created_at_idx')],
            },
        ),
    ]
