# Generated by Django 5.2.1 on 2025-07-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_scantrigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['name'], 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='fingerprinttemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='voter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='votingsession',
            options={'ordering': ['-start_time']},
        ),
        migrations.RenameIndex(
            model_name='scantrigger',
            new_name='voting_scan_is_used_37ad9e_idx',
            old_name='voting_scantrigger_is_used_idx',
        ),
        migrations.RenameIndex(
            model_name='scantrigger',
            new_name='voting_scan_created_c43f4e_idx',
            old_name='voting_scantrigger_created_at_idx',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='voter',
            name='has_voted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'post')},
        ),
    ]
