# Generated by Django 5.2.1 on 2025-07-29 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_activitylog_options_alter_candidate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprinttemplate',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.voter'),
        ),
    ]
