# Generated by Django 5.2.1 on 2025-07-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_alter_fingerprinttemplate_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantrigger',
            name='voter_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
