# Generated by Django 5.2.1 on 2025-07-31 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_alter_scantrigger_voter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantrigger',
            name='match_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scantrigger',
            name='match_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('not_found', 'Not Found'), ('already_voted', 'Already Voted'), ('error', 'Error')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='scantrigger',
            name='matched_voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_triggers', to='voting.voter'),
        ),
        migrations.AddIndex(
            model_name='scantrigger',
            index=models.Index(fields=['match_status'], name='voting_scan_match_s_bee273_idx'),
        ),
    ]
