# Generated by Django 5.2.1 on 2025-07-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_scantrigger_match_message_scantrigger_match_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scantrigger',
            name='voting_scan_is_used_37ad9e_idx',
        ),
        migrations.RemoveField(
            model_name='scantrigger',
            name='is_used',
        ),
        migrations.AddField(
            model_name='scantrigger',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scantrigger',
            name='used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='scantrigger',
            index=models.Index(fields=['used'], name='voting_scan_used_1f7998_idx'),
        ),
    ]
